import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppHeader, Card, SectionTitle, StatCard, StatGrid, TabButton, appStyles, sharedStyles } from '@/components/AppUI';
import { DataDashboard } from '@/components/DataDashboard';

const MERCHANT_ID = 'merchant_01';
type MerchantTab = 'overview' | 'data' | 'profile';

export default function MerchantScreen() {
  const [activeTab, setActiveTab] = useState<MerchantTab>('overview');

  return (
    <View style={sharedStyles.root}>
      <ScrollView contentContainerStyle={appStyles.screen}>
        <AppHeader
          title="Merchant"
          role="Merchant"
          subtitle="Own merchant_operations datasets generated by store activity."
        />

        {activeTab === 'overview' ? <OverviewTab /> : null}
        {activeTab === 'data' ? <DataDashboard role="merchant" userId={MERCHANT_ID} /> : null}
        {activeTab === 'profile' ? <ProfileTab /> : null}
      </ScrollView>

      <View style={sharedStyles.tabBar}>
        <TabButton label="Home" active={activeTab === 'overview'} onPress={() => setActiveTab('overview')} />
        <TabButton label="Data" active={activeTab === 'data'} onPress={() => setActiveTab('data')} />
        <TabButton label="Profile" active={activeTab === 'profile'} onPress={() => setActiveTab('profile')} />
      </View>
    </View>
  );
}

function OverviewTab() {
  return (
    <View style={appStyles.content}>
      <StatGrid>
        <StatCard label="Mock merchant" value={MERCHANT_ID} />
        <StatCard label="Data type" value="Ops" />
      </StatGrid>
      <SectionTitle>Protocol role</SectionTitle>
      <Card>
        <Text style={styles.title}>Merchant-owned operations data</Text>
        <Text style={appStyles.text}>
          Mars V4 treats menu, order, and merchant operations data as merchant-owned
          encrypted DataAssets with 100% ownership by the merchant.
        </Text>
      </Card>
      <View style={sharedStyles.bottomSpacer} />
    </View>
  );
}

function ProfileTab() {
  return (
    <View style={appStyles.content}>
      <Card>
        <Text style={styles.title}>Merchant profile</Text>
        <Text style={appStyles.text}>ID: {MERCHANT_ID}</Text>
        <Text style={appStyles.muted}>Demo identity only. Real Sui merchant identity is future work.</Text>
      </Card>
      <View style={sharedStyles.bottomSpacer} />
    </View>
  );
}

const styles = StyleSheet.create({
  title: {
    color: '#191919',
    fontSize: 20,
    fontWeight: '900',
  },
});
