import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppHeader, Card, SectionTitle, StatCard, StatGrid, TabButton, appStyles, sharedStyles } from '@/components/AppUI';
import { DataDashboard } from '@/components/DataDashboard';

const RIDER_ID = 'rider_01';
type RiderTab = 'overview' | 'data' | 'profile';

export default function RiderScreen() {
  const [activeTab, setActiveTab] = useState<RiderTab>('overview');

  return (
    <View style={sharedStyles.root}>
      <ScrollView contentContainerStyle={appStyles.screen}>
        <AppHeader
          title="Rider"
          role="Rider"
          subtitle="Own rider_mobility datasets generated by completed deliveries."
        />

        {activeTab === 'overview' ? <OverviewTab /> : null}
        {activeTab === 'data' ? <DataDashboard role="rider" userId={RIDER_ID} /> : null}
        {activeTab === 'profile' ? <ProfileTab /> : null}
      </ScrollView>

      <View style={sharedStyles.tabBar}>
        <TabButton label="Home" active={activeTab === 'overview'} onPress={() => setActiveTab('overview')} />
        <TabButton label="Data" active={activeTab === 'data'} onPress={() => setActiveTab('data')} />
        <TabButton label="Profile" active={activeTab === 'profile'} onPress={() => setActiveTab('profile')} />
      </View>
    </View>
  );
}

function OverviewTab() {
  return (
    <View style={appStyles.content}>
      <StatGrid>
        <StatCard label="Mock rider" value={RIDER_ID} />
        <StatCard label="Data type" value="Mobility" />
      </StatGrid>
      <SectionTitle>Protocol role</SectionTitle>
      <Card>
        <Text style={styles.title}>Rider-owned route data</Text>
        <Text style={appStyles.text}>
          Mars V4 treats rider mobility traces as rider-owned encrypted DataAssets.
          AI buyers must purchase a DataLicense before the Seal mock releases keys.
        </Text>
      </Card>
      <View style={sharedStyles.bottomSpacer} />
    </View>
  );
}

function ProfileTab() {
  return (
    <View style={appStyles.content}>
      <Card>
        <Text style={styles.title}>Rider profile</Text>
        <Text style={appStyles.text}>ID: {RIDER_ID}</Text>
        <Text style={appStyles.muted}>Demo identity only. Wallet and zkLogin are not connected yet.</Text>
      </Card>
      <View style={sharedStyles.bottomSpacer} />
    </View>
  );
}

const styles = StyleSheet.create({
  title: {
    color: '#191919',
    fontSize: 20,
    fontWeight: '900',
  },
});
