import { useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppHeader, Card, SectionTitle, StatCard, StatGrid, TabButton, appStyles, sharedStyles } from '@/components/AppUI';
import { DataDashboard } from '@/components/DataDashboard';

const CUSTOMER_ID = 'customer_01';
type CustomerTab = 'overview' | 'data' | 'profile';

export default function CustomerHomeScreen() {
  const [activeTab, setActiveTab] = useState<CustomerTab>('overview');

  return (
    <View style={sharedStyles.root}>
      <ScrollView contentContainerStyle={appStyles.screen}>
        <AppHeader
          title="Customer"
          role="Customer"
          subtitle="Own consumer_behavior datasets generated by delivery demand."
        />

        {activeTab === 'overview' ? <OverviewTab /> : null}
        {activeTab === 'data' ? <DataDashboard role="consumer" userId={CUSTOMER_ID} /> : null}
        {activeTab === 'profile' ? <ProfileTab /> : null}
      </ScrollView>

      <View style={sharedStyles.tabBar}>
        <TabButton label="Home" active={activeTab === 'overview'} onPress={() => setActiveTab('overview')} />
        <TabButton label="Data" active={activeTab === 'data'} onPress={() => setActiveTab('data')} />
        <TabButton label="Profile" active={activeTab === 'profile'} onPress={() => setActiveTab('profile')} />
      </View>
    </View>
  );
}

function OverviewTab() {
  return (
    <View style={appStyles.content}>
      <StatGrid>
        <StatCard label="Mock customer" value={CUSTOMER_ID} />
        <StatCard label="Data type" value="Behavior" />
      </StatGrid>
      <SectionTitle>Protocol role</SectionTitle>
      <Card>
        <Text style={styles.title}>Consumer-owned behavior data</Text>
        <Text style={appStyles.text}>
          Mars V4 treats consumer behavior data as consumer-owned encrypted DataAssets.
          This mock demo displays consumer-group assets generated by simulator packages.
        </Text>
      </Card>
      <View style={sharedStyles.bottomSpacer} />
    </View>
  );
}

function ProfileTab() {
  return (
    <View style={appStyles.content}>
      <Card>
        <Text style={styles.title}>Customer profile</Text>
        <Text style={appStyles.text}>ID: {CUSTOMER_ID}</Text>
        <Text style={appStyles.muted}>Demo identity only. Wallet, zkLogin, and checkout are not connected yet.</Text>
      </Card>
      <View style={sharedStyles.bottomSpacer} />
    </View>
  );
}

const styles = StyleSheet.create({
  title: {
    color: '#191919',
    fontSize: 20,
    fontWeight: '900',
  },
});
